name: poem

teacher_model: gpt-4-turbo

student_model: gpt-4

# maximum number of steps to optimize for
max_steps: 10

initial_prompt: "Can you write me a poem?"

feedback_type: {'r', 'hn', 'hp', 'fn', 'fp'}

syllable_req: [[4,5,4]]

ends_with: 'flourish'

context: 4